# Generated by Django 4.1.5 on 2024-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
